# Name of the Kind cluster
CLUSTER_NAME=multichannel

# Paths to the manifests generated by helmchart
FIRST_MANIFEST=./testing-pending-pod/pending-pod/pending-pod-1.yaml
SECOND_MANIFEST=./testing-pending-pod/pending-pod/pending-pod-2.yaml
THIRD_MANIFEST=./testing-pending-pod/pending-pod/pending-pod-3.yaml

# Target for creating the Kind cluster
.PHONY: create-cluster
create-cluster:
	@echo "Creating Kind cluster $(CLUSTER_NAME)..."
	kind create cluster --name $(CLUSTER_NAME)
	@echo "Waiting for the Kind cluster to be ready..."
	# Wait until the Kubernetes cluster is ready
	kubectl wait --for=condition=Ready nodes --all --timeout=300s
	# Check if the 'default' service account is ready before proceeding
	@echo "Checking if the 'default' service account is ready..."
	sleep 5

# Target for applying the first manifest
.PHONY: apply-first
apply-first: create-cluster
	@echo "Applying the first manifest: $(FIRST_MANIFEST)..."
	kubectl apply -f $(FIRST_MANIFEST)

# Target for applying the second manifest after waiting for 2 minutes
.PHONY: apply-second
apply-second: apply-first
	@echo "Waiting for 2 minutes..."
	sleep 120
	@echo "Applying the second manifest: $(SECOND_MANIFEST)..."
	kubectl apply -f $(SECOND_MANIFEST)

# Target for applying the third manifest after waiting for 2 minutes
.PHONY: apply-third
apply-third: apply-second
	@echo "Waiting for 2 minutes..."
	sleep 120
	@echo "Applying the third manifest: $(THIRD_MANIFEST)..."
	kubectl apply -f $(THIRD_MANIFEST)

# Main target that applies all manifests
.PHONY: apply-all
apply-all: apply-third
	@echo "All manifests have been applied."
