# Default values for my-pending-pods-chart.
# To generate 3 pod in 1 manifests helm template my-pending-pods-chart > all-pods.yaml

# List of pod names
pods:
  - pending-pod-1
  - pending-pod-2
  - pending-pod-3

# Node selector
nodeSelector:
  kubernetes.io/hostname: "non-existent-node"

# Container settings
container:
  name: busybox
  image: busybox
  command: ["sleep", "3600"]
